# -*- coding: utf-8 -*-
"""LMS_FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbMRnO4xXWU8M0pcIxh_aeGieKLmZlGr
"""

import os
import json
import time
import requests
import hashlib
import threading
from flask import Flask, jsonify
import flask
from flask_cors import CORS
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from html import escape
import psycopg2
from psycopg2.extras import RealDictCursor, Json

# ==========================================
# 1. API Key 與設定
# ==========================================
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

def safe_generate_text(prompt, fallback_text, timeout=35):
    try:
        response = model.generate_content(prompt, request_options={"timeout": timeout})
        text = getattr(response, "text", "").strip()
        return text or fallback_text
    except Exception as e:
        print(f"Gemini 生成失敗，使用備用回應: {e}")
        return fallback_text

#genai.configure(api_key=GEMINI_API_KEY)
#model = genai.GenerativeModel('gemini-2.5-flash')



GEMINI_MODEL = "gemini-2.5-flash"
GEMINI_CACHE = {}
MOOD_RECOMMENDATION_CACHE = {}
gemini_lock = threading.Lock()

COURSE_OPTIONS = [
    {
        "title": "情緒調節技能：考前 4-7-8 呼吸",
        "reason": "焦慮或壓力偏高時，先把身體警報降下來，再回到任務會更穩。",
        "difficulty": "入門",
        "tags": ["焦慮", "考試壓力"]
    },
    {
        "title": "壓力因應策略：學業壓力微計畫",
        "reason": "學業壓力明顯時，先把大任務拆成今天能開始的小步驟。",
        "difficulty": "入門",
        "tags": ["學業壓力", "任務拆解"]
    },
    {
        "title": "拖延行為重塑：番茄鐘微承諾",
        "reason": "出現逃避或滑手機慣性時，用短時間承諾降低啟動阻力。",
        "difficulty": "入門",
        "tags": ["拖延", "手機習慣"]
    },
    {
        "title": "社交焦慮管理：安全表達練習",
        "reason": "社交或上台壓力明顯時，先練習低風險表達，減少反覆預演。",
        "difficulty": "中階",
        "tags": ["社交壓力", "溝通"]
    },
    {
        "title": "睡眠壓力修復：睡前降速練習",
        "reason": "睡眠狀態會影響情緒與專注，先建立睡前降速流程。",
        "difficulty": "入門",
        "tags": ["睡眠", "恢復"]
    },
    {
        "title": "穩定狀態進階：專注節奏維持",
        "reason": "狀態相對穩定時，適合用更清楚的節奏維持學習表現。",
        "difficulty": "進階",
        "tags": ["穩定", "進階"]
    }
]

def to_int(value, default=0):
    try:
        return int(value)
    except Exception:
        return default

def build_context_key(data):
    parts = [
        str(data.get("user_id", "")),
        str(data.get("mood", "")),
        str(data.get("mood_score", "")),
        str(data.get("desc", "")),
        str(data.get("study_stress", "")),
        str(data.get("social_stress", "")),
        str(data.get("sleep_stress", ""))
    ]
    return hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()

def build_fallback_topics(data):
    mood_score = to_int(data.get("mood_score"), 3)
    study = to_int(data.get("study_stress"), 40)
    social = to_int(data.get("social_stress"), 20)
    sleep = to_int(data.get("sleep_stress"), 60)
    desc = str(data.get("desc", "")).lower()

    scores = [
        (COURSE_OPTIONS[0], (45 if mood_score >= 4 else 0) + study * 0.18),
        (COURSE_OPTIONS[1], study * 0.7 + (15 if any(k in desc for k in ["考", "報告", "作業", "讀"]) else 0)),
        (COURSE_OPTIONS[2], study * 0.25 + (55 if any(k in desc for k in ["拖延", "滑", "手機", "逃避", "不想"]) else 0)),
        (COURSE_OPTIONS[3], social * 0.75 + (35 if any(k in desc for k in ["社交", "同學", "上台", "報告", "訊息"]) else 0)),
        (COURSE_OPTIONS[4], sleep * 0.75),
        (COURSE_OPTIONS[5], 80 if mood_score <= 2 and study < 60 and social < 60 and sleep < 60 else 10)
    ]
    topics = [item for item, score in sorted(scores, key=lambda pair: pair[1], reverse=True) if score > 20]
    return topics[:2] or [COURSE_OPTIONS[0], COURSE_OPTIONS[1]]

def clean_json_text(text):
    return str(text or "").replace("```json", "").replace("```", "").strip()


def compact_ai_text(text, max_chars):
    """Keep AI feedback readable on mobile even when the model exceeds the prompt limit."""
    normalized = " ".join(str(text or "").split()).strip()
    if len(normalized) <= max_chars:
        return normalized

    preview = normalized[:max_chars]
    sentence_end = max(preview.rfind("。"), preview.rfind("！"), preview.rfind("？"))
    if sentence_end >= max_chars // 2:
        return preview[:sentence_end + 1]
    return preview.rstrip("，、；：,. ") + "…"

def safe_generate_text(prompt, fallback_text, timeout=35):
    if not GEMINI_API_KEY:
        return fallback_text

    api_key = GEMINI_API_KEY.strip()
    if api_key.startswith("$env:") or '"' in api_key or "'" in api_key:
        print("Gemini API Key 格式錯誤，請只設定金鑰本身，不要填入環境變數指令")
        return fallback_text

    cache_key = hashlib.sha256(f"{GEMINI_MODEL}|{prompt}".encode("utf-8")).hexdigest()
    if cache_key in GEMINI_CACHE:
        print("Gemini cache hit，使用快取結果")
        return GEMINI_CACHE[cache_key]

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent"
    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": api_key,
    }
    payload = {"contents": [{"parts": [{"text": prompt}]}]}
    session = requests.Session()
    session.trust_env = False
    retry_delays_429 = [8]
    retry_delays_5xx = [8]
    max_attempts = 2

    for attempt in range(max_attempts):
        try:
            with gemini_lock:
                r = session.post(url, headers=headers, json=payload, timeout=timeout)

            is_last_attempt = attempt == max_attempts - 1

            if r.status_code == 429:
                if is_last_attempt:
                    break

                retry_after = r.headers.get("Retry-After")
                delay = int(retry_after) if retry_after and retry_after.isdigit() else retry_delays_429[attempt]
                delay = min(delay, 5)

                print(f"Gemini 429 限流，第 {attempt + 1} 次等待 {delay} 秒後重試")
                time.sleep(delay)
                continue

            if r.status_code in [500, 502, 503, 504]:
                if is_last_attempt:
                    break

                delay = retry_delays_5xx[attempt]

                print(f"Gemini 暫時不可用，第 {attempt + 1} 次等待 {delay} 秒後重試: {r.status_code}")
                time.sleep(delay)
                continue

            if 400 <= r.status_code < 500:
                print(f"Gemini REST 設定或請求錯誤: HTTP {r.status_code}")
                break

            r.raise_for_status()
            data = r.json()
            text = data["candidates"][0]["content"]["parts"][0]["text"].strip()

            if text:
                GEMINI_CACHE[cache_key] = text
                return text

            return fallback_text

        except Exception as e:
            print(f"Gemini REST 第 {attempt + 1} 次失敗: {type(e).__name__}")

            if attempt < max_attempts - 1:
                time.sleep(3)

    print("Gemini REST 連續失敗，使用備用回應")
    return fallback_text

app = Flask(__name__)
CORS(app, allow_private_network=True)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


@app.route('/')
def serve_soulnav_app():
    return flask.send_from_directory(BASE_DIR, 'index.html')


@app.route('/soulsav-demo.css')
def serve_soulnav_styles():
    return flask.send_from_directory(BASE_DIR, 'soulsav-demo.css')


@app.route('/manifest.webmanifest')
def serve_web_manifest():
    return flask.send_from_directory(
        BASE_DIR,
        'manifest.webmanifest',
        mimetype='application/manifest+json',
    )


@app.route('/service-worker.js')
def serve_service_worker():
    response = flask.send_from_directory(
        BASE_DIR,
        'service-worker.js',
        mimetype='application/javascript',
    )
    response.headers['Cache-Control'] = 'no-cache'
    response.headers['Service-Worker-Allowed'] = '/'
    return response


@app.route('/assets/<path:filename>')
def serve_soulnav_asset(filename):
    return flask.send_from_directory(os.path.join(BASE_DIR, 'assets'), filename)


@app.route('/audio/<path:filename>')
def serve_soulnav_audio(filename):
    return flask.send_from_directory(os.path.join(BASE_DIR, 'audio'), filename)


@app.route('/health')
def health_check():
    return jsonify({"status": "ok", "service": "soulnav"})

# ==========================================
# 2. PostgreSQL 資料庫初始化與存取
# ==========================================
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = "postgresql://" + DATABASE_URL[len("postgres://"):]

PG_HOST = os.getenv("PG_HOST") or os.getenv("PGHOST", "localhost")
PG_PORT = int(os.getenv("PG_PORT") or os.getenv("PGPORT", "5432"))
PG_DATABASE = os.getenv("PG_DATABASE") or os.getenv("PGDATABASE", "soulnav_db")
PG_USER = os.getenv("PG_USER") or os.getenv("PGUSER", "postgres")
# 建議在 PowerShell 設定：$env:PG_PASSWORD="你的PostgreSQL密碼"
PG_PASSWORD = os.getenv("PG_PASSWORD") or os.getenv("PGPASSWORD", "")

def get_pg_conn():
    if DATABASE_URL:
        return psycopg2.connect(
            DATABASE_URL,
            cursor_factory=RealDictCursor,
        )
    return psycopg2.connect(
        host=PG_HOST,
        port=PG_PORT,
        database=PG_DATABASE,
        user=PG_USER,
        password=PG_PASSWORD,
        cursor_factory=RealDictCursor
    )

def init_pg_db():
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id VARCHAR(20) PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    account VARCHAR(100) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    last_login DATE,
                    badges INTEGER DEFAULT 0,
                    tasks_completed INTEGER DEFAULT 0,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cur.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_data JSONB DEFAULT '{}'::jsonb;")
            cur.execute("""
                CREATE TABLE IF NOT EXISTS behavior_logs (
                    id SERIAL PRIMARY KEY,
                    user_id VARCHAR(20) REFERENCES users(id) ON DELETE CASCADE,
                    action_type VARCHAR(100),
                    action_details JSONB,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS reflections (
                    id SERIAL PRIMARY KEY,
                    user_id VARCHAR(20) REFERENCES users(id) ON DELETE CASCADE,
                    reflection_id VARCHAR(120),
                    reflection_date DATE,
                    reflection_data JSONB,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
        conn.commit()

def normalize_date(value):
    if not value:
        return None
    text = str(value).strip().replace("/", "-")
    for fmt in ("%Y-%m-%d", "%Y-%m-%d %H:%M:%S"):
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            pass
    parts = text.split("-")
    if len(parts) == 3:
        try:
            year, month, day = [int(part) for part in parts]
            return datetime(year, month, day).date()
        except ValueError:
            return None
    return None

def row_to_user(row):
    if not row:
        return None
    profile = row.get("profile_data") or {}
    user = dict(profile)
    user.update({
        "id": row["id"],
        "user_id": row["id"],
        "account": row.get("account") or "",
        "name": row.get("name") or row.get("account") or "使用者",
        "password_hash": row.get("password") or "",
        "lastLogin": row.get("last_login").strftime("%Y-%m-%d") if row.get("last_login") else None,
        "badges": row.get("badges") or 0,
        "tasksCompleted": row.get("tasks_completed") or 0
    })
    user.setdefault("moodHistory", [])
    user.setdefault("recentActions", [])
    user.setdefault("recommendedTopics", [])
    user.setdefault("recommendationSnapshot", None)
    user.setdefault("inProgressCourse", None)
    user.setdefault("completedCourses", [])
    user.setdefault("completedLearningReports", [])
    user.setdefault("recommendationContextKey", None)
    user.setdefault("practiceHistory", [])
    user.setdefault("challengeProgress", {})
    user.setdefault("practiceProgressByKey", {})
    user.setdefault("dailyReflections", [])
    return user

def load_db():
    db = {"users": {}, "logs": [], "reflections": []}
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT * FROM users ORDER BY id;")
            for row in cur.fetchall():
                user = row_to_user(row)
                db["users"][user["id"]] = user

            cur.execute("SELECT * FROM behavior_logs ORDER BY created_at;")
            for row in cur.fetchall():
                details = row.get("action_details") or {}
                db["logs"].append({
                    "id": row.get("id"),
                    "user_id": row.get("user_id"),
                    "action_type": row.get("action_type"),
                    "action_details": details,
                    "timestamp": row.get("created_at").strftime("%Y-%m-%d %H:%M:%S") if row.get("created_at") else None
                })

            cur.execute("SELECT * FROM reflections ORDER BY created_at;")
            for row in cur.fetchall():
                data = row.get("reflection_data") or {}
                db["reflections"].append({
                    **data,
                    "id": row.get("id"),
                    "user_id": row.get("user_id"),
                    "reflection_id": row.get("reflection_id"),
                    "reflection_date": row.get("reflection_date").strftime("%Y-%m-%d") if row.get("reflection_date") else None,
                    "created_at": row.get("created_at").strftime("%Y-%m-%d %H:%M:%S") if row.get("created_at") else None,
                    "updated_at": row.get("updated_at").strftime("%Y-%m-%d %H:%M:%S") if row.get("updated_at") else None
                })
    return db

def save_db():
    global database
    database = load_db()

def upsert_user(user):
    profile = {
        key: value for key, value in user.items()
        if key not in {"id", "user_id", "account", "name", "password", "password_hash", "lastLogin", "last_login", "badges", "tasksCompleted", "tasks_completed"}
    }
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO users (id, name, account, password, last_login, badges, tasks_completed, profile_data)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (id) DO UPDATE SET
                    name = EXCLUDED.name,
                    account = EXCLUDED.account,
                    password = COALESCE(NULLIF(EXCLUDED.password, ''), users.password),
                    last_login = EXCLUDED.last_login,
                    badges = EXCLUDED.badges,
                    tasks_completed = EXCLUDED.tasks_completed,
                    profile_data = EXCLUDED.profile_data,
                    updated_at = CURRENT_TIMESTAMP;
            """, (
                user.get("id") or user.get("user_id"),
                user.get("name") or user.get("account") or "使用者",
                (user.get("account") or "").strip().lower(),
                user.get("password_hash") or user.get("password") or "",
                normalize_date(user.get("lastLogin") or user.get("last_login")),
                int(user.get("badges") or 0),
                int(user.get("tasksCompleted") or user.get("tasks_completed") or 0),
                Json(profile)
            ))
        conn.commit()

def get_user_by_id(user_id):
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT * FROM users WHERE id = %s;", (user_id,))
            return row_to_user(cur.fetchone())

def next_user_id():
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT id FROM users WHERE id LIKE 'LMS%' ORDER BY id DESC LIMIT 1;")
            row = cur.fetchone()
    if not row:
        return "LMS0001"
    try:
        return "LMS" + str(int(str(row["id"]).replace("LMS", "")) + 1).zfill(4)
    except ValueError:
        return "LMS0001"

def find_user_by_account(account):
    account = (account or "").strip().lower()
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT * FROM users WHERE LOWER(account) = %s;", (account,))
            return row_to_user(cur.fetchone())

database = {"users": {}, "logs": [], "reflections": []}

def initialize_database():
    global database
    init_pg_db()
    database = load_db()


def create_app():
    """Create the production app and initialize its cloud database."""
    initialize_database()
    return app

def public_user(user):
    safe = dict(user)
    safe.pop("password_hash", None)
    safe.pop("password", None)
    return safe
def create_empty_user(name, account, password):
    account = (account or "").strip().lower()
    user_id = next_user_id()

    user = {
        "id": user_id,
        "user_id": user_id,
        "account": account,
        "name": name or account,
        "password_hash": generate_password_hash(password),
        "streak": 0,
        "lastLogin": None,
        "badges": 0,
        "tasksCompleted": 0,
        "moodHistory": [],
        "recentActions": [],
        "recommendedTopics": [],
        "recommendationSnapshot": None,
        "inProgressCourse": None,
        "completedCourses": [],
        "completedLearningReports": [],
        "recommendationContextKey": None,
        "practiceHistory": [],
        "challengeProgress": {},
        "practiceProgressByKey": {},
        "dailyReflections": {}
    }

    upsert_user(user)
    save_db()
    return user
# ==========================================
# 3. 接收前端資料的 API 端點
# ==========================================

# (A) 註冊/更新使用者資訊
@app.route('/api/user/register', methods=['POST'])
def register_user():
    global database
    data = flask.request.json or {}

    # 情況 1：真正註冊新帳號
    if data.get("account") and data.get("password"):
        account = data.get("account").strip().lower()

        if find_user_by_account(account):
            return jsonify({"status": "error", "message": "這個帳號已經被註冊"}), 409

        user_id = next_user_id()
        user = {
            "id": user_id,
            "user_id": user_id,
            "account": account,
            "name": data.get("name", account),
            "password_hash": generate_password_hash(data.get("password")),
            "streak": 1,
            "lastLogin": None,
            "badges": 0,
            "tasksCompleted": 0,
            "moodHistory": [],
            "recentActions": [],
            "recommendedTopics": [],
            "recommendationSnapshot": None,
            "inProgressCourse": None,
            "completedCourses": [],
            "completedLearningReports": [],
            "recommendationContextKey": None,
            "practiceHistory": []
        }

        upsert_user(user)
        save_db()
        return jsonify({"status": "success", "user": public_user(user)})

    # 情況 2：前端同步使用者進度，保留原本密碼資料
    user_id = data.get("id") or data.get("user_id")
    if user_id:
        old_user = get_user_by_id(user_id)
        if not old_user:
            return jsonify({"status": "error", "message": "找不到使用者"}), 404

        password_hash = old_user.get("password_hash")
        account = old_user.get("account")

        old_user.update(data)
        old_user["id"] = user_id
        old_user["user_id"] = user_id
        if password_hash:
            old_user["password_hash"] = password_hash
        if account:
            old_user["account"] = account

        upsert_user(old_user)
        save_db()
        return jsonify({"status": "success", "user": public_user(old_user)})

    return jsonify({"status": "error", "message": "缺少註冊資料"}), 400


@app.route('/api/user/login', methods=['POST'])
def login_user():
    data = flask.request.json or {}
    account = data.get("account", "").strip().lower()
    password = data.get("password", "")

    user = find_user_by_account(account)
    if not user:
        return jsonify({"status": "error", "message": "找不到這個帳號"}), 404

    if not check_password_hash(user.get("password_hash", ""), password):
        return jsonify({"status": "error", "message": "密碼錯誤"}), 401

    return jsonify({"status": "success", "user": public_user(user)})

# (B) 萬用行為追蹤 (測驗、任務打勾、情境選擇都會送到這)
@app.route('/api/track', methods=['POST'])
def track_action():
    data = flask.request.json or {}
    data["timestamp"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO behavior_logs (user_id, action_type, action_details)
                VALUES (%s, %s, %s);
            """, (
                data.get("user_id"),
                data.get("action_type"),
                Json(data.get("action_details") or {})
            ))
        conn.commit()
    save_db()

    return jsonify({"status": "success"})

# (C) 最終反思與數據統整
@app.route('/api/reflection/submit', methods=['POST'])
def submit_reflection():
    data = flask.request.json or {}

    user_id = data.get("user_id")
    reflection_date = data.get("reflection_date")
    reflection_id = data.get("reflection_id")
    reflection_mode = data.get("reflection_mode")
    server_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    data["server_time"] = server_time

    updated = False
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            if reflection_mode == "upsert":
                cur.execute("""
                    SELECT id FROM reflections
                    WHERE user_id = %s
                      AND (
                        (%s <> '' AND reflection_id = %s)
                        OR (%s IS NOT NULL AND reflection_date = %s)
                      )
                    ORDER BY id DESC
                    LIMIT 1;
                """, (
                    user_id,
                    reflection_id or "",
                    reflection_id or "",
                    normalize_date(reflection_date),
                    normalize_date(reflection_date)
                ))
                existing = cur.fetchone()
                if existing:
                    cur.execute("""
                        UPDATE reflections
                        SET reflection_id = %s,
                            reflection_date = %s,
                            reflection_data = %s,
                            updated_at = CURRENT_TIMESTAMP
                        WHERE id = %s;
                    """, (
                        reflection_id,
                        normalize_date(reflection_date),
                        Json(data),
                        existing["id"]
                    ))
                    updated = True

            if not updated:
                cur.execute("""
                    INSERT INTO reflections (user_id, reflection_id, reflection_date, reflection_data)
                    VALUES (%s, %s, %s, %s);
                """, (
                    user_id,
                    reflection_id,
                    normalize_date(reflection_date),
                    Json(data)
                ))
        conn.commit()

    save_db()
    return jsonify({
        "status": "success",
        "mode": "updated" if reflection_mode == "upsert" and updated else "created"
    })

# ==========================================
# 4. 呼叫 Gemini AI 的 API 端點
# ==========================================

@app.route('/api/gemini/mood', methods=['POST'])
def analyze_mood():
    data = flask.request.json or {}
    context_key = build_context_key(data)
    if context_key in MOOD_RECOMMENDATION_CACHE:
        cached = dict(MOOD_RECOMMENDATION_CACHE[context_key])
        cached["status"] = "cache"
        cached["source"] = "cache"
        return jsonify(cached)

    fallback_topics = build_fallback_topics(data)
    fallback_analysis = "我有接收到你現在的壓力與情緒狀態。先不用急著把所有事一次解決，建議先做一個很小的穩定步驟，再回到任務。"
    course_titles = "\n".join([f"- {item['title']}" for item in COURSE_OPTIONS])

    prompt = f"""
你是 Navi AI 心理導航員。請根據學生狀態，回傳一個 JSON 物件，不要 markdown，不要額外說明。

學生狀態：
情緒：{data.get('mood')}
情緒分數：{data.get('mood_score')}
描述：{data.get('desc')}
學業壓力：{data.get('study_stress')}%
社交壓力：{data.get('social_stress')}%
睡眠壓力：{data.get('sleep_stress')}%

課程只能從以下固定課程選 2 個，不要自創課程名稱：
{course_titles}

JSON 格式：
{{
  "analysis": "繁體中文 60 到 90 字，溫暖同理，具體指出目前狀態與下一步",
  "recommended_topics": [
    {{"title": "固定課程名稱", "reason": "推薦原因", "difficulty": "入門", "tags": ["標籤1", "標籤2"]}},
    {{"title": "固定課程名稱", "reason": "推薦原因", "difficulty": "入門", "tags": ["標籤1", "標籤2"]}}
  ]
}}
"""

    text = safe_generate_text(prompt, "", timeout=35)
    result = None
    try:
        parsed = json.loads(clean_json_text(text))
        topics = parsed.get("recommended_topics") or parsed.get("topics") or []
        if isinstance(parsed, dict) and parsed.get("analysis") and isinstance(topics, list) and topics:
            result = {
                "status": "success",
                "source": "gemini",
                "analysis": parsed.get("analysis"),
                "topics": topics[:2],
                "recommended_topics": topics[:2]
            }
    except Exception as e:
        print(f"Gemini mood JSON 解析失敗，使用備用分析: {e}")

    if not result:
        result = {
            "status": "fallback",
            "source": "fallback",
            "analysis": fallback_analysis,
            "topics": fallback_topics,
            "recommended_topics": fallback_topics
        }

    MOOD_RECOMMENDATION_CACHE[context_key] = result
    return jsonify(result)

@app.route('/api/gemini/topics', methods=['POST'])
def gemini_topics():
    data = flask.request.json or {}
    context_key = build_context_key(data)

    if context_key in MOOD_RECOMMENDATION_CACHE:
        cached = MOOD_RECOMMENDATION_CACHE[context_key]
        return jsonify({
            "status": "cache",
            "source": "mood_cache",
            "topics": cached.get("recommended_topics", []),
            "recommended_topics": cached.get("recommended_topics", [])
        })

    fallback_topics = build_fallback_topics(data)
    MOOD_RECOMMENDATION_CACHE[context_key] = {
        "status": "fallback",
        "source": "local_fallback",
        "analysis": "目前先依照壓力量表與描述產生推薦課程，避免短時間重複呼叫 Gemini。",
        "topics": fallback_topics,
        "recommended_topics": fallback_topics
    }
    return jsonify({
        "status": "fallback",
        "source": "local_fallback",
        "topics": fallback_topics,
        "recommended_topics": fallback_topics
    })
@app.route('/api/gemini/task_breakdown', methods=['POST'])
def task_breakdown():
    data = flask.request.json or {}
    prompt = f"""
使用者目前任務：{data.get('task')}
剩餘時間：{data.get('time_left')}
目前狀態：{data.get('state')}
正在學習的課程：{data.get('active_course')}
系統內練習模組：{data.get('practice_modules')}

請根據使用者目前狀態，拆解成 5 到 7 個今天立刻能執行的小步驟。
每個步驟一行，不要 markdown，不要編號，不要多餘說明。
"""
    fallback = "寫下目前任務最小的一步\n準備需要用到的資料或工具\n先完成 5 分鐘的起始動作\n檢查卡住的地方並寫一句原因\n完成下一個 10 分鐘小段落"
    breakdown = safe_generate_text(prompt, fallback, timeout=35)
    return jsonify({"breakdown_text": breakdown})

@app.route('/api/gemini/insight', methods=['POST'])
def get_insight():
    data = flask.request.json or {}
    user_id = data.get("user_id")

    db = load_db()
    user = db.get("users", {}).get(user_id, {}) if user_id else {}

    user_logs = [
        log for log in db.get("logs", [])
        if log.get("user_id") == user_id
    ]

    recent_inputs = [
        log for log in user_logs
        if log.get("action_type") == "系統內練習輸入紀錄"
    ][-30:]

    recent_actions = user.get("recentActions", [])[-30:]
    recent_courses = user.get("completedCourses", [])[-10:]
    recent_reports = user.get("completedLearningReports", [])[-5:]

    recent_reflections = [
        ref for ref in db.get("reflections", [])
        if ref.get("user_id") == user_id
    ][-10:]

    if data.get("type") == "report":
        prompt = f"""
使用者完成了現實生活挑戰，請根據「本次回饋」做成果分析；其他紀錄只能作為輔助背景。

本次回饋：
{data.get('text')}

目前課程：
{data.get('active_course')}

本次挑戰進度：
{json.dumps(data.get('challenge_progress', {}), ensure_ascii=False)}

最近完成課程：
{json.dumps(recent_courses or data.get('completed_courses', []), ensure_ascii=False)}

最近系統內練習輸入：
{json.dumps(recent_inputs, ensure_ascii=False)}

最近行動紀錄：
{json.dumps(recent_actions or data.get('recent_actions', []), ensure_ascii=False)}

最近反思：
{json.dumps(recent_reflections, ensure_ascii=False)}

請用繁體中文回覆 30 到 40 字，限兩個短句，每句只保留一個重點。
第一句必須具體呼應「本次回饋」提到的行為、感受或困難，指出做得好的地方或卡點。
第二句只給一個與該回饋直接相關、可以立即執行的下一步。
不可只給通用鼓勵，不可加入使用者沒有提到的經歷；輸入不明確時，請指出需要再觀察的具體面向。
不要 markdown。
"""
        fallback = "你已經把練習帶進真實生活。下一次先保留最容易完成的一步。"

    elif data.get("type") == "final_summary":
        prompt = f"""
你是 Navi AI 心理導航員。請根據這位使用者最近的完整紀錄，產生個人化總結。

使用者基本狀態：
完成任務數：{user.get('tasksCompleted', data.get('tasks', 0))}
勳章數：{user.get('badges', data.get('badges', 0))}
連續打卡：{user.get('streak', data.get('streak', 0))}

最近完成課程：
{json.dumps(recent_courses, ensure_ascii=False)}

最近系統內練習輸入：
{json.dumps(recent_inputs, ensure_ascii=False)}

最近行動紀錄：
{json.dumps(recent_actions, ensure_ascii=False)}

最近現實挑戰回報：
{json.dumps(recent_reports, ensure_ascii=False)}

最近每日反思：
{json.dumps(recent_reflections, ensure_ascii=False)}

請回傳兩個短句、總長 50 到 65 字的繁體中文，每句只保留一個重點。
第一句合併最明顯的進展與反覆卡點，第二句只提出一個可執行調整。
內容要具體，不要只說「你很棒」。
不要 markdown。
"""
        fallback = "你已經能把想法轉成行動，但壓力升高時仍容易停住。下一步先固定一個最容易完成的小任務。"

    else:
        prompt = f"""
根據使用者最近紀錄給予專屬洞察。

完成任務數：{user.get('tasksCompleted', data.get('tasks_completed', 0))}
連續打卡：{user.get('streak', data.get('streak', 0))}

最近系統內練習輸入：
{json.dumps(recent_inputs, ensure_ascii=False)}

最近行動紀錄：
{json.dumps(recent_actions, ensure_ascii=False)}

最近完成課程：
{json.dumps(recent_courses, ensure_ascii=False)}

請用 Navi AI 心理導航員的口吻，給 30 到 40 字繁體中文，限兩個短句。
不要 markdown。
"""
        fallback = "你正在累積穩定行動。今天先維持一個容易完成的小步驟。"

    insight = safe_generate_text(prompt, fallback, timeout=40)
    insight_limit = 42 if data.get("type") == "report" else 68 if data.get("type") == "final_summary" else 42
    insight = compact_ai_text(insight, insight_limit)
    return jsonify({"insight": insight})

# (D) 讓您可以直接在網頁看資料庫的隱藏端點
@app.route('/api/admin/db', methods=['GET'])
def view_database():
    return jsonify(load_db())

def parse_json_field(raw, fallback=None):
    if not raw or not raw.strip():
        return fallback if fallback is not None else {}
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"JSON 格式錯誤：{exc}")

def redirect_to_user(user_id, tab="overview"):
    return flask.redirect(f"/admin/users/{user_id}#{tab}")

def count_completed_practice_modules(logs):
    count = 0
    for log in logs or []:
        if log.get("action_type") != "完成任務":
            continue
        details = log.get("action_details") or {}
        if isinstance(details, str):
            try:
                details = json.loads(details)
            except json.JSONDecodeError:
                details = {}
        item = str(details.get("項目", ""))
        if item.startswith("系統內練習："):
            count += 1
    return count

def summarize_user_stats(user, logs, reflections):
    courses = user.get("completedCourses", []) or []
    recent_actions = user.get("recentActions", []) or []
    mood_history = user.get("moodHistory", []) or []
    return {
        "completed_courses": len(courses),
        "practice_modules": count_completed_practice_modules(logs),
        "tasks_completed": user.get("tasksCompleted", 0),
        "badges": user.get("badges", 0),
        "logs_count": len(logs),
        "reflections_count": len(reflections),
        "recent_actions_count": len(recent_actions),
        "mood_count": len(mood_history),
    }

def admin_base_styles():
    return """
      <style>
        :root {
          --brand: #1f9c8d;
          --brand-dark: #14796f;
          --danger: #dc2626;
          --ink: #203238;
          --muted: #6f858b;
          --line: #dcebea;
          --bg: #f5fbfa;
          --panel: #ffffff;
          --soft: #eefaf7;
          --warn: #f2a51a;
          --info: #3f82f6;
        }
        * { box-sizing: border-box; }
        body {
          margin: 0;
          font-family: Arial, "Noto Sans TC", sans-serif;
          background: var(--bg);
          color: var(--ink);
        }
        .page {
          padding: 28px 40px;
        }
        .topbar {
          display: flex;
          align-items: flex-start;
          justify-content: space-between;
          gap: 16px;
          margin-bottom: 18px;
        }
        h1 { margin: 0 0 8px; font-size: 30px; }
        h2 { margin: 0 0 14px; font-size: 20px; }
        h3 { margin: 0 0 10px; font-size: 16px; }
        .sub { color: var(--muted); line-height: 1.6; }
        a { color: var(--brand-dark); text-decoration: none; font-weight: 700; }
        .panel {
          background: var(--panel);
          border: 1px solid var(--line);
          border-radius: 8px;
          box-shadow: 0 8px 24px rgba(20, 80, 80, 0.08);
          padding: 18px;
          margin-bottom: 16px;
        }
        .grid {
          display: grid;
          gap: 12px;
        }
        .grid.stats { grid-template-columns: repeat(6, minmax(120px, 1fr)); }
        .stat {
          border: 1px solid var(--line);
          background: #fbfefd;
          border-radius: 8px;
          padding: 14px;
          min-height: 82px;
        }
        .stat strong { display: block; font-size: 26px; color: var(--brand-dark); margin-bottom: 4px; }
        .stat span { color: var(--muted); font-size: 13px; }
        table {
          width: 100%;
          border-collapse: collapse;
          background: white;
          border-radius: 8px;
          overflow: hidden;
        }
        th, td {
          padding: 12px;
          border-bottom: 1px solid var(--line);
          text-align: left;
          font-size: 14px;
          vertical-align: top;
        }
        th { background: var(--brand); color: white; }
        tr:hover { background: var(--soft); }
        input, textarea, select {
          width: 100%;
          padding: 10px 12px;
          border: 1px solid var(--line);
          border-radius: 8px;
          background: white;
          font: inherit;
        }
        textarea { min-height: 96px; resize: vertical; font-family: Consolas, "Noto Sans TC", monospace; }
        label { display: block; color: var(--muted); font-size: 13px; font-weight: 700; margin-bottom: 6px; }
        .form-grid {
          display: grid;
          grid-template-columns: repeat(4, minmax(160px, 1fr));
          gap: 12px;
          align-items: end;
        }
        .form-grid.two { grid-template-columns: 1fr 1fr; }
        .form-grid.three { grid-template-columns: repeat(3, minmax(160px, 1fr)); }
        .full { grid-column: 1 / -1; }
        button, .button {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          border: 0;
          border-radius: 8px;
          padding: 10px 14px;
          background: var(--brand);
          color: white;
          font-weight: 800;
          cursor: pointer;
          min-height: 40px;
        }
        .button.secondary, button.secondary { background: #e8f4f2; color: var(--brand-dark); }
        .delete-btn, button.danger { background: var(--danger); }
        .actions { display: flex; gap: 8px; flex-wrap: wrap; }
        .tabs {
          display: flex;
          gap: 8px;
          flex-wrap: wrap;
          margin: 18px 0;
        }
        .tabs a {
          padding: 10px 14px;
          border-radius: 8px;
          background: #e8f4f2;
          color: var(--brand-dark);
        }
        .section { display: none; }
        .section:target { display: block; }
        .section.default { display: block; }
        body:has(.section:target) .section.default:not(:target) { display: none; }
        .chip {
          display: inline-flex;
          padding: 5px 8px;
          border-radius: 999px;
          background: #e8f4f2;
          color: var(--brand-dark);
          font-size: 12px;
          font-weight: 800;
        }
        .bar {
          height: 10px;
          background: #e5f0ef;
          border-radius: 999px;
          overflow: hidden;
        }
        .bar span {
          display: block;
          height: 100%;
          background: linear-gradient(90deg, var(--brand), var(--info));
        }
        pre {
          white-space: pre-wrap;
          background:#f7fbfb;
          border: 1px solid var(--line);
          padding:12px;
          border-radius:8px;
          max-height: 320px;
          overflow: auto;
        }
        .muted { color: var(--muted); }
        .compact td { font-size: 13px; }
        @media (max-width: 980px) {
          .page { padding: 20px; }
          .grid.stats, .form-grid, .form-grid.two, .form-grid.three { grid-template-columns: 1fr; }
          .topbar { flex-direction: column; }
        }
      </style>
    """

@app.route('/admin/users/create', methods=['POST'])
def admin_create_user():
    name = flask.request.form.get("name", "").strip()
    account = flask.request.form.get("account", "").strip().lower()
    password = flask.request.form.get("password", "").strip()

    if not account or not password:
        return "帳號與密碼不可空白", 400

    if len(password) < 6:
        return "密碼至少需要 6 個字元", 400

    if find_user_by_account(account):
        return "這個帳號已經存在", 409

    create_empty_user(name, account, password)
    return flask.redirect("/admin/users")


@app.route('/admin/users/<user_id>/delete', methods=['POST'])
def admin_delete_user(user_id):
    if not get_user_by_id(user_id):
        return "找不到使用者", 404

    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM users WHERE id = %s;", (user_id,))
        conn.commit()
    save_db()
    return flask.redirect("/admin/users")

@app.route('/admin/users/<user_id>/update', methods=['POST'])
def admin_update_user(user_id):
    user = get_user_by_id(user_id)
    if not user:
        return "找不到使用者", 404

    account = flask.request.form.get("account", "").strip().lower()
    if not account:
        return "帳號不可空白", 400

    existing = find_user_by_account(account)
    if existing and existing.get("id") != user_id:
        return "這個帳號已經存在", 409

    user["name"] = flask.request.form.get("name", "").strip() or account
    user["account"] = account
    user["lastLogin"] = flask.request.form.get("last_login", "").strip() or None
    user["badges"] = int(flask.request.form.get("badges") or 0)
    user["tasksCompleted"] = int(flask.request.form.get("tasks_completed") or 0)

    new_password = flask.request.form.get("password", "").strip()
    if new_password:
        if len(new_password) < 6:
            return "密碼至少需要 6 個字元", 400
        user["password_hash"] = generate_password_hash(new_password)

    upsert_user(user)
    save_db()
    return redirect_to_user(user_id, "profile")

@app.route('/admin/users/<user_id>/logs/create', methods=['POST'])
def admin_create_log(user_id):
    if not get_user_by_id(user_id):
        return "找不到使用者", 404

    action_type = flask.request.form.get("action_type", "").strip()
    if not action_type:
        return "行為類型不可空白", 400
    try:
        details = parse_json_field(flask.request.form.get("action_details", ""), {})
    except ValueError as exc:
        return str(exc), 400

    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO behavior_logs (user_id, action_type, action_details)
                VALUES (%s, %s, %s);
            """, (user_id, action_type, Json(details)))
        conn.commit()
    save_db()
    return redirect_to_user(user_id, "logs")

@app.route('/admin/logs/<int:log_id>/delete', methods=['POST'])
def admin_delete_log(log_id):
    user_id = flask.request.form.get("user_id", "")
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM behavior_logs WHERE id = %s;", (log_id,))
        conn.commit()
    save_db()
    return redirect_to_user(user_id, "logs") if user_id else flask.redirect("/admin/users")

@app.route('/admin/users/<user_id>/reflections/create', methods=['POST'])
def admin_create_reflection(user_id):
    if not get_user_by_id(user_id):
        return "找不到使用者", 404

    reflection_id = flask.request.form.get("reflection_id", "").strip() or None
    reflection_date = flask.request.form.get("reflection_date", "").strip() or None
    try:
        reflection_data = parse_json_field(flask.request.form.get("reflection_data", ""), {})
    except ValueError as exc:
        return str(exc), 400
    reflection_data["user_id"] = user_id
    if reflection_id:
        reflection_data["reflection_id"] = reflection_id
    if reflection_date:
        reflection_data["reflection_date"] = reflection_date

    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO reflections (user_id, reflection_id, reflection_date, reflection_data)
                VALUES (%s, %s, %s, %s);
            """, (user_id, reflection_id, normalize_date(reflection_date), Json(reflection_data)))
        conn.commit()
    save_db()
    return redirect_to_user(user_id, "reflections")

@app.route('/admin/reflections/<int:reflection_pk>/update', methods=['POST'])
def admin_update_reflection(reflection_pk):
    user_id = flask.request.form.get("user_id", "")
    reflection_id = flask.request.form.get("reflection_id", "").strip() or None
    reflection_date = flask.request.form.get("reflection_date", "").strip() or None
    try:
        reflection_data = parse_json_field(flask.request.form.get("reflection_data", ""), {})
    except ValueError as exc:
        return str(exc), 400
    if user_id:
        reflection_data["user_id"] = user_id
    if reflection_id:
        reflection_data["reflection_id"] = reflection_id
    if reflection_date:
        reflection_data["reflection_date"] = reflection_date

    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                UPDATE reflections
                SET reflection_id = %s,
                    reflection_date = %s,
                    reflection_data = %s,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = %s;
            """, (reflection_id, normalize_date(reflection_date), Json(reflection_data), reflection_pk))
        conn.commit()
    save_db()
    return redirect_to_user(user_id, "reflections") if user_id else flask.redirect("/admin/users")

@app.route('/admin/reflections/<int:reflection_pk>/delete', methods=['POST'])
def admin_delete_reflection(reflection_pk):
    user_id = flask.request.form.get("user_id", "")
    with get_pg_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM reflections WHERE id = %s;", (reflection_pk,))
        conn.commit()
    save_db()
    return redirect_to_user(user_id, "reflections") if user_id else flask.redirect("/admin/users")

@app.route('/admin/users', methods=['GET'])
def admin_users_table():
    db = load_db()
    users = db.get("users", {})
    logs = db.get("logs", [])
    reflections = db.get("reflections", [])

    rows = []

    for user_id, user in users.items():
        user_logs = [log for log in logs if log.get("user_id") == user_id]
        user_refs = [ref for ref in reflections if ref.get("user_id") == user_id]
        practice_done_count = count_completed_practice_modules(user_logs)

        rows.append({
            "user_id": user_id,
            "name": user.get("name", ""),
            "account": user.get("account", ""),
            "last_login": user.get("lastLogin") or user.get("last_login", ""),
            "completed_courses": len(user.get("completedCourses", [])),
            "practice_modules": practice_done_count,
            "tasks_completed": user.get("tasksCompleted", 0),
            "badges": user.get("badges", 0),
            "logs_count": len(user_logs),
            "reflections_count": len(user_refs),
        })

    html = """
    <!DOCTYPE html>
    <html lang="zh-Hant">
    <head>
      <meta charset="UTF-8">
      <title>SoulNav 使用者紀錄總覽</title>
      """ + admin_base_styles() + """
    </head>
    <body>
      <div class="page">
        <div class="topbar">
          <div>
            <h1>SoulNav 使用者紀錄總覽</h1>
            <div class="sub">可查看每位使用者的課程、練習、任務、反思與行為紀錄數量。</div>
          </div>
          <input id="userFilter" style="max-width:280px;" placeholder="搜尋姓名、帳號或 ID">
        </div>

        <div class="panel">
          <h2>新增使用者</h2>
          <form method="post" action="/admin/users/create">
            <div class="form-grid">
              <div><label>姓名</label><input name="name" placeholder="姓名"></div>
              <div><label>帳號</label><input name="account" placeholder="帳號" required></div>
              <div><label>密碼</label><input name="password" placeholder="密碼至少 6 位" required></div>
              <div><button type="submit">新增使用者</button></div>
            </div>
          </form>
        </div>

        <table id="userTable">
        <tr>
          <th>使用者ID</th>
          <th>姓名</th>
          <th>帳號</th>
          <th>最後登入</th>
          <th>完成課程</th>
          <th>系統練習</th>
          <th>完成任務</th>
          <th>勳章</th>
          <th>行為紀錄</th>
          <th>反思紀錄</th>
          <th>操作</th>
        </tr>
    """

    for row in rows:
        row_user_id = escape(str(row["user_id"]))
        row_search = escape(" ".join([
            str(row["user_id"]),
            str(row["name"]),
            str(row["account"])
        ]).lower())
        html += f"""
        <tr data-user-search="{row_search}" onclick="location.href='/admin/users/{row_user_id}'" style="cursor:pointer">
          <td>{escape(str(row["user_id"]))}</td>
          <td>{escape(str(row["name"]))}</td>
          <td>{escape(str(row["account"]))}</td>
          <td>{escape(str(row["last_login"]))}</td>
          <td>{row["completed_courses"]}</td>
          <td>{row["practice_modules"]}</td>
          <td>{row["tasks_completed"]}</td>
          <td>{row["badges"]}</td>
          <td>{row["logs_count"]}</td>
          <td>{row["reflections_count"]}</td>
          <td onclick="event.stopPropagation()">
            <form method="post" action="/admin/users/{row_user_id}/delete" onsubmit="return confirm('確定要刪除這位使用者與所有相關紀錄嗎？');">
              <button class="delete-btn" type="submit">刪除</button>
            </form>
          </td>
        </tr>
        """

    html += """
      </table>
      </div>
      <script>
        const userFilter = document.getElementById('userFilter');
        if (userFilter) {
          userFilter.addEventListener('input', () => {
            const keyword = userFilter.value.trim().toLowerCase();
            document.querySelectorAll('#userTable tr[data-user-search]').forEach(row => {
              row.style.display = row.dataset.userSearch.includes(keyword) ? '' : 'none';
            });
          });
        }
      </script>
    </body>
    </html>
    """

    return html

@app.route('/admin/users/<user_id>', methods=['GET'])
def admin_user_detail(user_id):
    db = load_db()
    user = db.get("users", {}).get(user_id)
    if not user:
        return "找不到使用者", 404

    logs = [
        log for log in db.get("logs", [])
        if log.get("user_id") == user_id
    ]

    reflections = [
        ref for ref in db.get("reflections", [])
        if ref.get("user_id") == user_id
    ]

    stats = summarize_user_stats(user, logs, reflections)
    recent_logs = list(reversed(logs))[:30]
    recent_reflections = list(reversed(reflections))[:20]
    tasks_width = min(100, int(stats["tasks_completed"] or 0))
    badges_width = min(100, int(stats["badges"] or 0) * 10)
    courses_width = min(100, stats["completed_courses"] * 12)
    practice_width = min(100, stats["practice_modules"] * 4)
    user_json = escape(json.dumps(user, ensure_ascii=False, indent=2, default=str))
    logs_json = escape(json.dumps(logs, ensure_ascii=False, indent=2, default=str))
    reflections_json = escape(json.dumps(reflections, ensure_ascii=False, indent=2, default=str))

    log_rows = ""
    for log in recent_logs:
        detail_text = json.dumps(log.get("action_details", {}), ensure_ascii=False, indent=2, default=str)
        log_id = log.get("id")
        log_rows += f"""
          <tr data-action="{escape(str(log.get('action_type', ''))).lower()}">
            <td><span class="chip">#{escape(str(log_id))}</span></td>
            <td>{escape(str(log.get("timestamp") or ""))}</td>
            <td>{escape(str(log.get("action_type") or ""))}</td>
            <td><pre>{escape(detail_text)}</pre></td>
            <td>
              <form method="post" action="/admin/logs/{escape(str(log_id))}/delete" onsubmit="return confirm('確定刪除這筆行為紀錄嗎？');">
                <input type="hidden" name="user_id" value="{escape(user_id)}">
                <button class="danger" type="submit">刪除</button>
              </form>
            </td>
          </tr>
        """

    if not log_rows:
        log_rows = '<tr><td colspan="5" class="muted">目前沒有行為紀錄。</td></tr>'

    reflection_blocks = ""
    for ref in recent_reflections:
        ref_id = ref.get("id")
        ref_text = escape(json.dumps(ref, ensure_ascii=False, indent=2, default=str))
        reflection_blocks += f"""
          <div class="panel">
            <form method="post" action="/admin/reflections/{escape(str(ref_id))}/update">
              <input type="hidden" name="user_id" value="{escape(user_id)}">
              <div class="form-grid three">
                <div>
                  <label>資料庫 ID</label>
                  <input value="{escape(str(ref_id))}" disabled>
                </div>
                <div>
                  <label>反思 ID</label>
                  <input name="reflection_id" value="{escape(str(ref.get("reflection_id") or ""))}">
                </div>
                <div>
                  <label>反思日期</label>
                  <input name="reflection_date" value="{escape(str(ref.get("reflection_date") or ref.get("date") or ""))}" placeholder="YYYY-MM-DD">
                </div>
                <div class="full">
                  <label>反思資料 JSON</label>
                  <textarea name="reflection_data">{ref_text}</textarea>
                </div>
              </div>
              <div class="actions" style="margin-top:12px;">
                <button type="submit">儲存修改</button>
              </div>
            </form>
            <form method="post" action="/admin/reflections/{escape(str(ref_id))}/delete" onsubmit="return confirm('確定刪除這筆反思紀錄嗎？');">
              <input type="hidden" name="user_id" value="{escape(user_id)}">
              <button class="danger" type="submit">刪除</button>
            </form>
          </div>
        """

    if not reflection_blocks:
        reflection_blocks = '<div class="panel muted">目前沒有反思紀錄。</div>'

    html = f"""
    <!DOCTYPE html>
    <html lang="zh-Hant">
    <head>
      <meta charset="utf-8">
      <title>{escape(user_id)} 使用者詳細紀錄</title>
      {admin_base_styles()}
    </head>
    <body>
      <div class="page">
        <div class="topbar">
          <div>
            <h1>{escape(user.get("name", ""))} 的資料庫紀錄</h1>
            <div class="sub">使用者 ID：{escape(user_id)}　帳號：{escape(user.get("account", ""))}</div>
          </div>
          <a class="button secondary" href="/admin/users">返回總覽</a>
        </div>

        <div class="tabs">
          <a href="#overview">總覽</a>
          <a href="#profile">基本資料</a>
          <a href="#logs">行為紀錄</a>
          <a href="#reflections">反思紀錄</a>
          <a href="#raw">原始資料</a>
        </div>

        <section id="overview" class="section default">
          <div class="grid stats">
            <div class="stat"><strong>{stats["completed_courses"]}</strong><span>完成課程</span></div>
            <div class="stat"><strong>{stats["practice_modules"]}</strong><span>系統練習</span></div>
            <div class="stat"><strong>{stats["tasks_completed"]}</strong><span>完成任務</span></div>
            <div class="stat"><strong>{stats["badges"]}</strong><span>勳章</span></div>
            <div class="stat"><strong>{stats["logs_count"]}</strong><span>行為紀錄</span></div>
            <div class="stat"><strong>{stats["reflections_count"]}</strong><span>反思紀錄</span></div>
          </div>

          <div class="panel">
            <h2>學習狀態視覺化</h2>
            <div class="grid" style="grid-template-columns: 1fr 1fr; gap:16px;">
              <div>
                <label>任務完成進度</label>
                <div class="bar"><span style="width:{tasks_width}%"></span></div>
              </div>
              <div>
                <label>勳章累積</label>
                <div class="bar"><span style="width:{badges_width}%"></span></div>
              </div>
              <div>
                <label>課程完成量</label>
                <div class="bar"><span style="width:{courses_width}%"></span></div>
              </div>
              <div>
                <label>練習紀錄量</label>
                <div class="bar"><span style="width:{practice_width}%"></span></div>
              </div>
            </div>
          </div>

          <div class="panel">
            <h2>最近行為紀錄</h2>
            <table class="compact">
              <tr><th>時間</th><th>類型</th></tr>
              {''.join(f"<tr><td>{escape(str(log.get('timestamp') or ''))}</td><td>{escape(str(log.get('action_type') or ''))}</td></tr>" for log in recent_logs[:8]) or '<tr><td colspan="2" class="muted">沒有紀錄</td></tr>'}
            </table>
          </div>
        </section>

        <section id="profile" class="section">
          <div class="panel">
            <h2>修改使用者基本資料</h2>
            <form method="post" action="/admin/users/{escape(user_id)}/update">
              <div class="form-grid three">
                <div>
                  <label>姓名</label>
                  <input name="name" value="{escape(str(user.get("name", "")))}" required>
                </div>
                <div>
                  <label>帳號</label>
                  <input name="account" value="{escape(str(user.get("account", "")))}" required>
                </div>
                <div>
                  <label>新密碼</label>
                  <input name="password" type="password" placeholder="不修改可留空">
                </div>
                <div>
                  <label>最後登入</label>
                  <input name="last_login" value="{escape(str(user.get("lastLogin") or ""))}" placeholder="YYYY-MM-DD">
                </div>
                <div>
                  <label>完成任務</label>
                  <input name="tasks_completed" type="number" min="0" value="{escape(str(user.get("tasksCompleted", 0)))}">
                </div>
                <div>
                  <label>勳章</label>
                  <input name="badges" type="number" min="0" value="{escape(str(user.get("badges", 0)))}">
                </div>
              </div>
              <div class="actions" style="margin-top:12px;">
                <button type="submit">儲存使用者</button>
              </div>
            </form>
          </div>
        </section>

        <section id="logs" class="section">
          <div class="panel">
            <h2>新增行為紀錄</h2>
            <form method="post" action="/admin/users/{escape(user_id)}/logs/create">
              <div class="form-grid two">
                <div>
                  <label>行為類型</label>
                  <input name="action_type" placeholder="例如：管理者補登任務" required>
                </div>
                <div class="full">
                  <label>紀錄內容 JSON</label>
                  <textarea name="action_details">{{"note": "補登紀錄"}}</textarea>
                </div>
              </div>
              <div class="actions" style="margin-top:12px;"><button type="submit">新增紀錄</button></div>
            </form>
          </div>

          <div class="panel">
            <div class="topbar">
              <div>
                <h2>行為紀錄查詢與刪除</h2>
                <div class="sub">顯示最近 30 筆，可用類型關鍵字篩選。</div>
              </div>
              <input id="logFilter" style="max-width:280px;" placeholder="搜尋 action type">
            </div>
            <table class="compact" id="logTable">
              <tr><th>ID</th><th>時間</th><th>類型</th><th>內容</th><th>操作</th></tr>
              {log_rows}
            </table>
          </div>
        </section>

        <section id="reflections" class="section">
          <div class="panel">
            <h2>新增反思紀錄</h2>
            <form method="post" action="/admin/users/{escape(user_id)}/reflections/create">
              <div class="form-grid three">
                <div>
                  <label>反思 ID</label>
                  <input name="reflection_id" placeholder="{escape(user_id)}::YYYY-MM-DD">
                </div>
                <div>
                  <label>反思日期</label>
                  <input name="reflection_date" placeholder="YYYY-MM-DD">
                </div>
                <div class="full">
                  <label>反思資料 JSON</label>
                  <textarea name="reflection_data">{{"choice": "今天的反思", "note": "管理者新增"}}</textarea>
                </div>
              </div>
              <div class="actions" style="margin-top:12px;"><button type="submit">新增反思</button></div>
            </form>
          </div>
          {reflection_blocks}
        </section>

        <section id="raw" class="section">
          <div class="panel">
            <h2>使用者原始資料</h2>
            <pre>{user_json}</pre>
          </div>
          <div class="panel">
            <h2>行為紀錄原始資料</h2>
            <pre>{logs_json}</pre>
          </div>
          <div class="panel">
            <h2>反思紀錄原始資料</h2>
            <pre>{reflections_json}</pre>
          </div>
        </section>
      </div>

      <script>
        const filter = document.getElementById('logFilter');
        if (filter) {{
          filter.addEventListener('input', () => {{
            const keyword = filter.value.trim().toLowerCase();
            document.querySelectorAll('#logTable tr[data-action]').forEach(row => {{
              row.style.display = row.dataset.action.includes(keyword) ? '' : 'none';
            }});
          }});
        }}
      </script>
    </body>
    </html>
    """

    return html


# ==========================================
# 5. 啟動伺服器
# ==========================================
if __name__ == '__main__':
    initialize_database()
    db = load_db()
    print("使用者數：", len(db.get("users", {})))
    print("行為紀錄數：", len(db.get("logs", [])))
    print("反思紀錄數：", len(db.get("reflections", [])))
    print(f"====================================================")
    print(f"SoulNav 後端已啟動！")
    port = int(os.getenv("PORT", "5000"))
    debug_mode = os.getenv("FLASK_DEBUG", "").lower() in {"1", "true", "yes"}
    print(f"電腦開啟: http://127.0.0.1:{port}")
    print(f"手機請開啟電腦的區域網路 IP，連接埠為 {port}")
    print(f"即時資料庫 JSON: http://127.0.0.1:{port}/api/admin/db")
    print(f"使用者資料表: http://127.0.0.1:{port}/admin/users")
    print(f"====================================================")

    app.run(host="0.0.0.0", port=port, debug=debug_mode)

'''

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models.py
# import json
# from sqlalchemy import create_engine, Column, Integer, String, Text, DateTime
# from sqlalchemy.orm import sessionmaker, declarative_base
# from sqlalchemy.sql import func
# 
# DATABASE_URL = "sqlite:///./soulnav.db"
# engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
# SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
# 
# Base = declarative_base()
# 
# class User(Base):
#     __tablename__ = 'users'
#     id = Column(Integer, primary_key=True, index=True)
#     user_lms_id = Column(String(50), unique=True)
#     name = Column(String(50))
#     streak = Column(Integer, default=1)
#     badges = Column(Integer, default=0)
#     completed_tasks = Column(Integer, default=0)
#     last_login = Column(String(50), nullable=True)
# 
# class UserActionLog(Base):
#     __tablename__ = 'user_action_logs'
#     id = Column(Integer, primary_key=True, index=True)
#     user_lms_id = Column(String(50))
#     action_type = Column(String(100))
#     action_details = Column(Text)
#     created_at = Column(DateTime(timezone=True), server_default=func.now())
# 
# def init_db():
#     Base.metadata.create_all(bind=engine)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from fastapi import FastAPI, Depends
# from fastapi.middleware.cors import CORSMiddleware
# from pydantic import BaseModel
# from sqlalchemy.orm import Session
# from typing import Any, Dict
# import json
# #import google.generativeai as genai
# from google.colab import userdata
# import models
# 
# # ── 初始化 Gemini API ──
# GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
# genai.configure(api_key=GEMINI_API_KEY)
# 
# # 使用 gemini-1.5-flash-8b (Flash-Lite 輕量版)
# model = genai.GenerativeModel('gemini-2.5-flash')
# 
# app = FastAPI(title="SoulNav 核心系統")
# models.init_db()
# 
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"],
# )
# 
# def get_db():
#     db = models.SessionLocal()
#     try: yield db
#     finally: db.close()
# 
# # 定義接收的資料結構
# class ActionSubmit(BaseModel):
#     user_id: str
#     action_type: str
#     action_details: Dict[str, Any]
# 
# class UserSync(BaseModel):
#     user_id: str
#     name: str
#     streak: int
#     badges: int
#     last_login: str | None
# 
# class ReflectSubmit(BaseModel):
#     user_id: str
#     reflect_choice: str
#     final_badges: int
#     final_streak: int
#     mood_text_snapshot: str
# 
# # 1. 萬用追蹤 API
# @app.post("/api/track")
# def track_action(data: ActionSubmit, db: Session = Depends(get_db)):
# 
#     log = models.UserActionLog(
#         user_lms_id=data.user_id,
#         action_type=data.action_type,
#         action_details=json.dumps(data.action_details, ensure_ascii=False)
#     )
# 
#     db.add(log)
#     db.commit()
# 
#     # AI Topic Recommendation
#     if data.action_type == "/api/ai/topics":
# 
#         details = data.action_details
# 
#         study = int(details.get("study_stress", 0))
#         social = int(details.get("social_stress", 0))
#         sleep = int(details.get("sleep_stress", 0))
# 
#         topics = []
# 
#         # 高學業壓力
#         if study >= 70:
#             topics.append({
#                 "title": "壓力應對策略",
#                 "reason": "目前偵測到較高學業壓力。",
#                 "difficulty": "入門",
#                 "emotional_tags": ["壓力", "焦慮"]
#             })
# 
#         # 高社交壓力
#         if social >= 70:
#             topics.append({
#                 "title": "社交焦慮克服",
#                 "reason": "目前偵測到較高社交壓力。",
#                 "difficulty": "中階",
#                 "emotional_tags": ["社交", "焦慮"]
#             })
# 
#         # 睡眠問題
#         if sleep >= 70:
#             topics.append({
#                 "title": "情緒調節技巧",
#                 "reason": "目前偵測到睡眠與情緒壓力。",
#                 "difficulty": "入門",
#                 "emotional_tags": ["睡眠", "情緒"]
#             })
# 
#         # 拖延 / 沒動力
#         if "拖延" in mood or "沒動力" in mood:
#             topics.append({
#                 "title": "拖延行為重塑",
#                 "reason": "AI 偵測到拖延與低動力傾向。",
#                 "difficulty": "中階",
#                 "emotional_tags": ["拖延"]
#             })
# 
#         # fallback
#         if not topics:
#             topics.append({
#                 "title": "情緒調節技巧",
#                 "reason": "維持穩定情緒與自我覺察。",
#                 "difficulty": "入門",
#                 "emotional_tags": ["情緒"]
#             })
# 
#         return {
#             "topics": topics
#         }
# 
#     return {
#         "status": "success"
#     }
# 
# # 2. 獲取圖表用的歷史紀錄 API
# @app.get("/api/track/history/{user_id}")
# def get_history(user_id: str, db: Session = Depends(get_db)):
#     logs = db.query(models.UserActionLog).filter(models.UserActionLog.user_lms_id == user_id).all()
#     return [{"type": l.action_type, "details": json.loads(l.action_details)} for l in logs]
# 
# # 3. 同步使用者設定 API
# @app.post("/api/user/register")
# def sync_user(data: UserSync, db: Session = Depends(get_db)):
#     user = db.query(models.User).filter(models.User.user_lms_id == data.user_id).first()
#     if not user:
#         user = models.User(user_lms_id=data.user_id, name=data.name, streak=data.streak, badges=data.badges, last_login=data.last_login)
#         db.add(user)
#     else:
#         user.streak, user.badges, user.last_login = data.streak, data.badges, data.last_login
#     db.commit()
#     return {"status": "success"}
# 
# # 4. 結算反思 API
# @app.post("/api/reflection/submit")
# def submit_reflect(data: ReflectSubmit, db: Session = Depends(get_db)):
#     log = models.UserActionLog(
#         user_lms_id=data.user_id, action_type="Step 5 - 最終結算送出",
#         action_details=json.dumps(data.model_dump(), ensure_ascii=False)
#     )
#     db.add(log)
#     db.commit()
#     return {"status": "success"}
# 
# # 5. Gemini: 情緒評估
# @app.post("/api/ai/mood")
# def ai_mood(data: Dict[str, Any]):
#     prompt = f"使用者心情: {data['mood']} ({data['score']}分)\n發生了什麼: {data['desc']}\n壓力來源: 學業{data['study']}%, 社交{data['social']}%, 睡眠{data['sleep']}%\n請扮演心理導航員 Navi。給出3句溫暖專業的簡短分析。最後加粗體字：「建議立即執行『情緒調節 + 拖延症重塑』練習路徑。」直接輸出HTML格式，不要包含 ```html。"
#     try:
#         response = model.generate_content(prompt)
#         return {"html": response.text.replace("```html", "").replace("```", "").strip()}
#     except:
#         return {"html": f"<strong>建議立即執行『情緒調節 + 拖延症重塑』練習路徑。</strong>"}
# 
# # 6. Gemini: 任務拆解
# @app.post("/api/ai/task")
# def ai_task(data: Dict[str, Any]):
#     prompt = f"任務: {data['task']}\n時間: {data['time']}\n狀態: {data['state']}\n拆解3-4個微小步驟。嚴格回傳JSON：{{\"summary\":\"一句話鼓勵\",\"naviTip\":\"目前狀態為『{data['state']}』，每完成五個任務會獲1枚勳章，動手就贏了！\",\"steps\":[{{\"title\":\"步驟\",\"duration\":\"5 分鐘\",\"tag\":\"準備\"}}]}}。不要有 ```json 標籤。"
#     try:
#         response = model.generate_content(prompt)
#         clean = response.text.replace("```json", "").replace("```", "").strip()
#         return json.loads(clean)
#     except:
#         return {"summary": "分析失敗", "naviTip": f"目前狀態為「{data['state']}」，每完成五個任務就會獲得 1 枚勳章，動手就贏了！", "steps": [{"title":"寫第一段","duration":"10分鐘","tag":"準備"}]}
# 
# # 7. Gemini: 綜合洞察
# @app.post("/api/ai/insights")
# def ai_insights(data: Dict[str, Any]):
#     prompt = f"完成任務數: {data['completed_tasks']}\n心得回報: {data['report']}\n給出專屬分析。回傳嚴格JSON：{{\"insights\":[{{\"type\":\"success或warning或info\",\"text\":\"一句話分析\"}}],\"navi_msgs\":[\"Navi鼓勵1\",\"Navi建議2\"]}}。不要 ```json。"
#     try:
#         response = model.generate_content(prompt)
#         clean = response.text.replace("```json", "").replace("```", "").strip()
#         return json.loads(clean)
#     except:
#         return {"insights": [{"type":"info","text":"持續打卡建立健康習慣！"}], "navi_msgs": ["這週很棒，請繼續保持！"]}

import nest_asyncio
from pyngrok import ngrok
import uvicorn
import asyncio
import requests
import hashlib
import threading
import base64
import re
from google.colab import userdata

nest_asyncio.apply()

NGROK_TOKEN = "REMOVED_NGROK_TOKEN"
GEMINI_API_KEY = "REMOVED_GEMINI_API_KEY"
ngrok.set_auth_token(NGROK_TOKEN)
genai.configure(api_key=GEMINI_API_KEY)

try:
    public_url = ngrok.connect(8000).public_url
    print("=" * 60)
    print(f"🎉 ngrok 網址：{public_url}")
    print("=" * 60)
except Exception as e:
    print(f"ngrok 連線失敗: {e}")

REPO = "owo0511/soulnav"
FILE_PATH = "index.html"
headers = {"Authorization": f"token {GITHUB_TOKEN}"}

# 修正了這裡的乾淨網址
r = requests.get(f"https://api.github.com/repos/{REPO}/contents/{FILE_PATH}", headers=headers)
data = r.json()
if "sha" not in data:
    raise Exception(f"找不到 GitHub 檔案，請確認 Token 權限。錯誤訊息: {data}")

sha = data["sha"]
content = base64.b64decode(data["content"]).decode("utf-8")

# 自動替換 index.html 中的 CLOUD_BASE_URL
new_content = re.sub(
    r'const CLOUD_BASE_URL = ".*?";',
    f'const CLOUD_BASE_URL = "{public_url}";',
    content
)

encoded = base64.b64encode(new_content.encode("utf-8")).decode("utf-8")
requests.put(
    f"https://api.github.com/repos/{REPO}/contents/{FILE_PATH}",
    headers=headers,
    json={"message": "auto update ngrok URL", "content": encoded, "sha": sha}
)
print("✅ index.html 已自動更新到 GitHub！約 30 秒後學生網頁生效。")

config = uvicorn.Config("main:app", host="127.0.0.1", port=8000, log_level="info")
server = uvicorn.Server(config)
loop = asyncio.get_event_loop()
loop.create_task(server.serve())

try:
    del request
except NameError:
    pass

import sqlite3
import models
from sqlalchemy import create_engine

# 1. 強制讓 models 使用與 main.py 一樣的資料庫連線
# 確保 models.py 內的 DATABASE_URL = "sqlite:////content/soulnav.db"
# 然後重新初始化
models.init_db()

# 2. 測試資料庫連線路徑
try:
    conn = sqlite3.connect("/content/soulnav.db")
    cursor = conn.cursor()
    # 檢查 table 是否存在
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='user_action_logs'")
    if cursor.fetchone():
        print("✅ user_action_logs 表格確實存在於資料庫中！")
    else:
        print("❌ 警告：表格不存在，請確認 models.init_db() 是否執行成功。")
    conn.close()
except Exception as e:
    print(f"錯誤: {e}")

import pandas as pd
import json

# 讀取剛剛存下來的資料庫檔案
try:
    with open(DB_FILE, 'r', encoding='utf-8') as f:
        db = json.load(f)

    print("=========== 👥 使用者名單 ===========")
    if db['users']:
        users_df = pd.DataFrame.from_dict(db['users'], orient='index')
        display(users_df)
    else:
        print("目前無使用者註冊。")

    print("\n=========== 👣 行為追蹤紀錄 ===========")
    if db['logs']:
        logs_df = pd.DataFrame(db['logs'])
        display(logs_df)
    else:
        print("目前無行為紀錄。")

    print("\n=========== 📝 最終反思總結 ===========")
    if db['reflections']:
        ref_df = pd.DataFrame(db['reflections'])
        display(ref_df)
    else:
        print("目前無反思紀錄。")

except FileNotFoundError:
    print("找不到 soulnav_db.json 檔案，請確認伺服器有收到資料並存檔喔！")

import pandas as pd
import json

# 讀取剛剛存下來的資料庫檔案
try:
    with open('soulnav_db.json', 'r', encoding='utf-8') as f:
        db = json.load(f)

    print("=========== 👥 使用者名單 ===========")
    if db['users']:
        users_df = pd.DataFrame.from_dict(db['users'], orient='index')
        display(users_df)
    else:
        print("目前無使用者註冊。")

    print("\n=========== 👣 行為追蹤紀錄 ===========")
    if db['logs']:
        logs_df = pd.DataFrame(db['logs'])
        display(logs_df)
    else:
        print("目前無行為紀錄。")

    print("\n=========== 📝 最終反思總結 ===========")
    if db['reflections']:
        ref_df = pd.DataFrame(db['reflections'])
        display(ref_df)
    else:
        print("目前無反思紀錄。")

except FileNotFoundError:
    print("找不到 soulnav_db.json 檔案，請確認伺服器有收到資料並存檔喔！")

"""### ⚠️ 請確認您的 API Key 已設定

您在執行 `sKWxbglizcuL` 儲存格時，遇到了 `SecretNotFoundError`，表示 `NGROK_TOKEN` 尚未在 Colab 的 secrets manager 中設定。同時，為了讓 AI API 正常運作，也請確認 `GEMINI_API_KEY` 已經設定完成。

請依照以下步驟設定您的 API Keys：

1.  點擊 Colab 左側工具欄的「🔑」圖示 (Secrets)。
2.  新增兩個 Secret：
    *   **Name**: `NGROK_TOKEN`，**Value**: 您的 ngrok Auth Token (可以從 [ngrok 官網](https://dashboard.ngrok.com/get-started/your-authtoken) 取得)。
    *   **Name**: `GEMINI_API_KEY`，**Value**: 您的 Gemini API Key (可以從 [Google AI Studio](https://aistudio.google.com/app/apikey) 取得)。
3.  勾選「Notebook access」以允許筆記本存取這些 Secret。

設定完成後，請重新運行之前的程式碼儲存格，特別是 `sKWxbglizcuL` 和 `J-mt__bvzZp2`，確保所有服務都能正常啟動。然後，您可以執行下面的測試儲存格來驗證 AI API 的連接狀況。
"""

import requests
import json

# Assuming public_url is already defined from the previous cell
# If you rerun the notebook, you might need to re-run the ngrok setup cell

if 'public_url' not in locals():
    print("錯誤：ngrok public_url 未定義。請先運行 ngrok 連線的儲存格。")
else:
    print(f"嘗試連接到 AI API: {public_url}/api/ai/mood")
    test_data = {
        "mood": "開心",
        "score": 5,
        "desc": "今天學到了新東西！",
        "study": 10,
        "social": 5,
        "sleep": 0
    }
    try:
        response = requests.post(f"{public_url}/api/ai/mood", json=test_data)
        response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
        result = response.json()
        print("\n✅ AI API 連接成功！返回的分析結果：")
        print(json.dumps(result, ensure_ascii=False, indent=2))
    except requests.exceptions.RequestException as e:
        print(f"\n❌ AI API 連接失敗或發生錯誤: {e}")
        print("請檢查：")
        print("1. ngrok 是否已成功啟動並取得 public_url。")
        print("2. `main.py` 中的 FastAPI 應用是否正在運行。")
        print("3. `GEMINI_API_KEY` 是否已正確設定在 Colab secrets 中。")
'''
